# Generated by Django 3.2.4 on 2021-06-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='profile pic')),
                ('background_pic', models.ImageField(upload_to='background pic')),
                ('feature_pic', models.ImageField(upload_to='feature pics')),
            ],
        ),
    ]
